[package]
name = "llamars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizers = "0.15.0"
memmap2 = "0.9.0"
rayon = "1.8"
clap = { version = "4.4.11", features = ["derive"] }
imap = "3.0.0-alpha.12"
tokio = { version = "1.35.0", features = ["full"] }
serde = { version = "1.0.193", features = ["derive"] }
bincode = "1.3.3"
mailparse = "0.14.0"
toml = "0.8.8"
csv = "1.3.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
debug = 1
