title = "Config"

[server]
model = "mistral"
port = 5000
prompts = [
    { name = "efficiency", prefix = """
You are an engineer who wants to make machine learning run faster.

Explain if the scientific paper improves the speed of machine learning algorithms.

Output Format:
###Explanation###
###Answer (yes or no)###

###Paper###
""", postfix = """

###Explanation###
Let,s think step by step.""", output_len = 100 },
]
