title = "Config"

[server]
model = "models/mixtral"
port = 5000
prompts = [
    { name = "papers", prefix = """
Is the following paper better than existing methods on many tasks?

Output Format:
Explanation:
Answer: yes or no

Paper:
""", postfix = """

Explanation:
""", output_len = 500 },
]
