title = "Config"

[server]
model = "models/mixtral"
port = 5000
prompts = [
    { name = "papers", prefix = """
[INST] Is the following paper better than existing methods on many tasks? You must answer either yes or no.

Output Format:
Explanation:
Answer: yes or no

Paper:
""", postfix = """

[/INST]""", output_len = 500 },
]
