title = "Config"

[server]
weights = "weights.bin"
port = 5000
prompts = [
    {name = "topic", prefix = "Classify the title into one of the topics \"Language Models\", \"Computer Vision\", \"Reinforcement Learning\", \"Other\".\nTitle: Language Models are Few-Shot Learners\nTopic: Language Models\nTitle: ImageNet Classification with Deep Convolutional Neural Networks\nTopic: Computer Vision\nTitle: Trust Region Policy Optimization\nTopic: Reinforcement Learning\nTitle: A Mathematical Theory of Communication\nTopic: Other\nTitle:", postfix = "\nTopic:", output_len = 5},
]
