title = "Config"

[server]
weights = "weights.bin"
port = 5000
prompts = [
    {name = "ml", prefix = "Is the following title of a scientific paper about the topic machine learning? Answer yes or no.\nTitle: ImageNet Classification with Deep Convolutional Neural Networks\nAnswer: yes\nTitle: A Mathematical Theory of Communication\nAnswer: no\nTitle:", postfix = "\nAnswer:", output_len = 1},
]
