title = "Config"

[server]
weights = "weights"
port = 5000
prompts = [
    { name = "papers", prefix = """
[INST] Is the main topic of the following paper about running language models more efficiently?

Paper:
""", postfix = """

Answer Format:
{
    Explanation: _,
    Yes or No: _,
}

Answer:
[/INST]""", output_len = 256 },
]
